# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_auto_20170422_2040'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u0431\u043b\u043e\u0433\u0430',
                'verbose_name_plural': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u0431\u043b\u043e\u0433\u0430',
            },
        ),
        migrations.CreateModel(
            name='CommentsNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='\u041d\u043e\u0432\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043d\u043e\u0432\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439',
            },
        ),
    ]
